SELECT S.YEAR, (S.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM ECOLI_DATA D,
    (
        SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) S
WHERE YEAR(D.DIFFERENTIATION_DATE) = S.YEAR 
ORDER BY YEAR, YEAR_DEV